// <auto-generated />
using System;
using InsureApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsureApp.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20190108165334_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsureApp.Entities.Concrete.Arac", b =>
                {
                    b.Property<int>("Arac_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Arac_turu");

                    b.Property<string>("Plaka");

                    b.Property<int>("Police_no");

                    b.Property<string>("Ruhsat_no");

                    b.HasKey("Arac_id");

                    b.ToTable("Arac");
                });

            modelBuilder.Entity("InsureApp.Entities.Concrete.Konut_Diger", b =>
                {
                    b.Property<int>("Konut_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres");

                    b.Property<int>("Police_no");

                    b.HasKey("Konut_id");

                    b.ToTable("Konut_Diger");
                });

            modelBuilder.Entity("InsureApp.Entities.Concrete.Musteri", b =>
                {
                    b.Property<int>("Musteri_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .IsRequired();

                    b.Property<string>("Isim")
                        .IsRequired();

                    b.Property<string>("Ozel_not");

                    b.Property<string>("Soyisim")
                        .IsRequired();

                    b.Property<long>("Tc_No");

                    b.Property<long>("Tel_no");

                    b.HasKey("Musteri_id");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("InsureApp.Entities.Concrete.Odemeler", b =>
                {
                    b.Property<int>("Odeme_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Musteri_id");

                    b.Property<DateTime>("Odeme_tarihi");

                    b.Property<int>("Odenen_tutar");

                    b.Property<int>("Police_no");

                    b.HasKey("Odeme_id");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("InsureApp.Entities.Concrete.Police", b =>
                {
                    b.Property<int>("Police_no")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Baslangic_tarihi");

                    b.Property<DateTime>("Bitis_tarihi");

                    b.Property<int>("Musteri_id");

                    b.Property<int>("Policetur_id");

                    b.Property<int>("Sigorta_bedeli");

                    b.Property<DateTime>("Vize_tarihi");

                    b.HasKey("Police_no");

                    b.ToTable("Police");
                });

            modelBuilder.Entity("InsureApp.Entities.Concrete.Police_Turu", b =>
                {
                    b.Property<int>("Policetur_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Police_turu");

                    b.HasKey("Policetur_id");

                    b.ToTable("Police_Turu");
                });
#pragma warning restore 612, 618
        }
    }
}
